// <auto-generated />
using Devopsweb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Devopsweb.Migrations
{
    [DbContext(typeof(SkillsDbContext))]
    [Migration("20240924094324_AddImageUrlToSkills")]
    partial class AddImageUrlToSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Devopsweb.Models.SkillsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "",
                            Title = "MySQL"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "",
                            Title = "HTML"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "",
                            Title = "CSS"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "",
                            Title = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "",
                            Title = "Java"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "",
                            Title = "Kotlin"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "",
                            Title = "C#"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "",
                            Title = "OOP"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "",
                            Title = "JSON"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "",
                            Title = "JDBC"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "",
                            Title = "Github"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "",
                            Title = "Bootstrap"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "",
                            Title = "Spring Framework"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
