name: C# CI With dotnet

on:
    push:
        branches: ["master"]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.400'

    - name: Restore dependencies
      run: dotnet restore Devopsweb.csproj

    - name: Listing files
      run: ls

    - name: Build project
      run: dotnet build Devopsweb.csproj --configuration Release --no-restore
     
    

    - name: Run tests
      run: dotnet test /home/runner/work/Devopsweb/DevopswebTests/Controllers/HomeControllerTests.cs
      continue-on-error: false

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      if: success()  
      with:
        image: filipdetterfelt/portfolio
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      if: success()  
      with:
        service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api-key: ${{ secrets.MY_RENDER_API_KEY }}
        wait-for-success: false